### ISSUE TITLE
Huginn Catalog doesn't run til the end

### ISSUE THREAD

**Issue by enekenasoa** [rancher-cowboys/catalog#3]
After running the catalog, the stack remains on "Activating" state... 
It may lasts a couples of hours and go on "Unhealthy" state. 
mysql container seems to be ok but huginn-threaded and huginn-web couldn't be activated.
It tries to activate them again and again....

![huginn1](https://cloud.githubusercontent.com/assets/28084961/25475717/670b48e6-2b40-11e7-87fc-7eb13a3e25b0.png)
![huginn2](https://cloud.githubusercontent.com/assets/28084961/25475741/7426917a-2b40-11e7-85e0-7d6f0485525b.png)
![huginn3](https://cloud.githubusercontent.com/assets/28084961/25476024/6e8c31f6-2b41-11e7-909d-c222b20d0600.png)

Anyone know how to troubleshoot/fix this issue? 
Thanks

**Comment by elboletaire** [comment]
The huginn repo in this catalog has never been working. You can take a look to the PR #2 where @gtrias pasted the `docker-compose.yml` that he had working. 

If you finally have it working don't hesitate to open a PR 😄

**Comment by gtrias** [comment]
@enekenasoa can you provide some logs? Maybe I could help setting up the container

**Comment by enekenasoa** [comment]
Hi,

Here the logs of each containers... 


Thanks
[huginn2-huginn-threaded-1.txt](https://github.com/rancher-cowboys/catalog/files/961555/huginn2-huginn-threaded-1.txt)
[huginn2-huginn-web-1.txt](https://github.com/rancher-cowboys/catalog/files/961554/huginn2-huginn-web-1.txt)

**Comment by elboletaire** [comment]
Please, take a look to the comment by @gtrias in #2, where you can take a newer version of the  `docker-compose.yml` file.

The logs you passed show you're trying to connect to `your-domain-here.com` which is an example url that remains there since we tried it for the first time.

**Comment by gtrias** [comment]
It seems one of your containers cannot connect to mysql because credentials. Are the same mysql parameters for the three containers?

**Comment by enekenasoa** [comment]
I've run the updated `docker-compose.yml` file by @gtrias. And on logs, I had _`"huginn" database missing`_
So, I've added in `docker-compose.yml` :

_mysql : 
     image : mysql
     environment : 
         **MYSQL_DATABASE: huginn**_

Then, i got this error messages : 
_4/28/2017 12:16:03 PM/app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:218:in `query': Mysql2::Error: Table 'huginn.agents' doesn't exist: SHOW FULL FIELDS FROM `agents` (ActiveRecord::StatementInvalid)
4/28/2017 12:16:03 PM	from /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:218:in `block in execute'
4/28/2017 12:16:03 PM	from /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:589:in `block in log'
4/28/2017 12:16:03 PM	from /app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
4/28/2017 12:16:03 PM	from /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:583:in `log'
4/28/2017 12:16:03 PM	from /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:218:in `execute'
4/28/2017 12:16:03 PM	from /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/mysql/database_statements.rb:31:in `execute'
4/28/2017 12:16:03 PM	from /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:225:in `execute_and_free'
4/28/2017 12:16:03 PM	from /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:885:in `column_definitions'
4/28/2017 12:16:03 PM	from /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:400:in `columns'
4/28/2017 12:16:03 PM	from /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/schema_cache.rb:56:in `columns'
4/28/2017 12:16:03 PM	from /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/schema_cache.rb:62:in `columns_hash'
4/28/2017 12:16:03 PM	from /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/model_schema.rb:441:in `load_schema!'
4/28/2017 12:16:03 PM	from /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/attributes.rb:233:in `load_schema!'
4/28/2017 12:16:03 PM	from /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/attribute_decorators.rb:28:in `load_schema!'
4/28/2017 12:16:03 PM	from /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/model_schema.rb:436:in `load_schema'
4/28/2017 12:16:03 PM	from /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/model_schema.rb:339:in `columns_hash'
4/28/2017 12:16:03 PM	from /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/inheritance.rb:77:in `descends_from_active_record?'
4/28/2017 12:16:03 PM	from /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/inheritance.rb:83:in `finder_needs_type_condition?'
4/28/2017 12:16:03 PM	from /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/core.rb:292:in `relation'
4/28/2017 12:16:03 PM	from /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/scoping/named.rb:38:in `default_scoped'
4/28/2017 12:16:03 PM	from /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/scoping/named.rb:28:in `all'
4/28/2017 12:16:03 PM	from /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/scoping/named.rb:159:in `block in scope'
4/28/2017 12:16:03 PM	from /app/app/models/agents/twitter_stream_agent.rb:128:in `setup_worker'
4/28/2017 12:16:03 PM	from /app/lib/agent_runner.rb:94:in `block (2 levels) in load_workers'
4/28/2017 12:16:03 PM	from /app/lib/agent_runner.rb:62:in `block in with_connection'
4/28/2017 12:16:03 PM	from /app/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:398:in `with_connection'
4/28/2017 12:16:03 PM	from /app/lib/agent_runner.rb:61:in `with_connection'
4/28/2017 12:16:03 PM	from /app/lib/agent_runner.rb:93:in `block in load_workers'
4/28/2017 12:16:03 PM	from /app/lib/agent_runner.rb:89:in `each'
4/28/2017 12:16:03 PM	from /app/lib/agent_runner.rb:89:in `load_workers'
4/28/2017 12:16:03 PM	from /app/lib/agent_runner.rb:69:in `run_workers'
4/28/2017 12:16:03 PM	from /app/lib/agent_runner.rb:39:in `run'
4/28/2017 12:16:03 PM	from bin/threaded.rb:13:in `<top (required)>'
4/28/2017 12:16:03 PM	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.1/lib/rails/commands/runner.rb:60:in `load'
4/28/2017 12:16:03 PM	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.1/lib/rails/commands/runner.rb:60:in `<top (required)>'
4/28/2017 12:16:03 PM	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:138:in `require'
4/28/2017 12:16:03 PM	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:138:in `require_command!'
4/28/2017 12:16:03 PM	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:104:in `runner'
4/28/2017 12:16:03 PM	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
4/28/2017 12:16:03 PM	from /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.1/lib/rails/commands.rb:18:in `<top (required)>'
4/28/2017 12:16:03 PM	from bin/rails:9:in `require'
4/28/2017 12:16:03 PM	from bin/rails:9:in `<main>'_
         
I guess there are missing fields here...
